### ISSUE TITLE
[Bug]: Wrong type “postCode”

### ISSUE THREAD

**Issue by eric2905** [iobroker-community-adapters/ioBroker.tankerkoenig#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adapter version 3.3.1

Log:
```
tankerkoenig.0 | 2023-01-01 07:43:25.973 | info | State value to set for "tankerkoenig.0.stations.5.postCode" has to be type "string" but received type "number"

tankerkoenig.0 | 2023-01-01 07:43:25.870 | info | State value to set for "tankerkoenig.0.stations.4.postCode" has to be type "string" but received type "number"
```

### Adapter version

3.3.1

**Comment by xXBJXx** [comment]
Fixed in Version 3.3.2

**Comment by Grothesk242** [comment]
Bug is still existing in V3.3.5. 
I deleted all objects and also did create new stations. 

```
2023-01-13 20:24:54.698  - warn: tankerkoenig.0 (410804) Post code type is number in config from station Star must be have type string. Please check your configuration or reconfigure the stations => edit station => save
2023-01-13 20:24:54.699  - warn: tankerkoenig.0 (410804) Post code type is number in config from station Shell must be have type string. Please check your configuration or reconfigure the stations => edit station => save
```

**Comment by Grothesk242** [comment]
Didn't work like this. I deleted everything and now it works.
